name: Build OS

on:
  push:
    branches:
      - "stable"
      - "unstable"
      - "testing"
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build.
        run: |
          sudo ./build.sh
